#!/bin/bash

set -o pipefail -o errexit -o noclobber -o nounset

die() {
    printf '%s\n' "$@"
    exit 1
}

script_dir="$(cd "$(dirname "$0")" && pwd)"

format_script="$script_dir/format-kt-files"


unformatted_files="$($format_script --dry-run --set-exit-if-changed )" \
    || \
    die "Incorrectly formatted files found:" "$unformatted_files"

