#!/bin/bash

set -o pipefail -o errexit -o noclobber -o nounset

die() {
    printf '%s\n' "$@"
    exit 1
}

formatting_style="kotlinlang-style"

project_root="$(git rev-parse --show-toplevel)"
ktfmt="$project_root/tools/ktfmt/ktfmt"

find "$project_root" \
    \( \
    -iname '*.kt' \
    -o \
    -iname '*.kts' \
    \) \
    -exec "$ktfmt" \
    --set-exit-if-changed \
    "--$formatting_style" \
    "$@" \
    '{}' +


