#!/bin/bash

set -o errexit -o nounset -o pipefail

function bail() {
	echo "$1"
	exit 1
}

compose_file="$(git rev-parse --show-toplevel)/integration-tests/firebase/docker-compose.yml"
[[ -f "$compose_file" ]] || bail "Can't find docker compose file at ${compose_file}"

docker compose -f "${compose_file}" up --wait
