#!/bin/bash

set -o errexit -o nounset -o pipefail

function bail() {
	echo "$1"
	exit 1
}

project_name="${1:-$(basename "$(git rev-parse --show-toplevel)")}"
[[ -n "$project_name" ]] || bail "No project name given"
echo "Project name: $project_name"

firestore_rules="${2:-$(git rev-parse --show-toplevel)/firestore.rules}"
[[ -f "$firestore_rules" ]] || bail "File $firestore_rules doesn't exist"
echo "Firestore rules file: $firestore_rules"

image="ghcr.io/grodin/firebase-emulator-docker"

docker pull "${image}:latest"

function cleanup() {
  docker rm -f firebase-emulator > /dev/null 2>&1
}

trap cleanup SIGTERM SIGINT

ui_port=4000
ui_websocket_port=9150
ui_logging_port=4500
hub_port=4400
auth_port=9099
firestore_port=8080
local_firestore_port="${DEBUG_FIRESTORE_PORT:-$firestore_port}"


docker run -it \
    --rm \
    --publish "$ui_port":"$ui_port" \
    --publish "$ui_websocket_port":"$ui_websocket_port" \
    --publish "$ui_logging_port":"$ui_logging_port" \
    --publish "$hub_port":"$hub_port" \
    --publish "$auth_port":"$auth_port" \
    --publish "$local_firestore_port":"$firestore_port" \
    --name firebase-emulator \
    --volume "$firestore_rules:/home/firestore-emulator/firestore.rules" \
    "${image}" \
 	emulators:start --project "$project_name"

cleanup
