version: "3.7"
services:
  firebase-emulator:
    image: 'ghcr.io/grodin/firebase-emulator-docker@sha256:a77edbf687cbc2f574735b101b814829abd0e4ce28b7bb9bc241ea6746003ce6'
    volumes:
      - ../..:/home/firestore-emulator
      - type: bind
        source: ../../firestore.rules
        target: /home/firebase-emulator/firestore.rules
    ports:
      - 4000:4000
      - 9150:9150
      - 4500:4500
      - 4400:4400
      - 9099:9099
      - 8080:8080
    healthcheck:
      timeout: 120s
    entrypoint:
      - "firebase"
      - "emulators:start"
      - "--project"
      - "map-librarian"
