version: "3.7"
services:
  firebase-emulator:
    image: 'ghcr.io/grodin/firebase-emulator-docker@sha256:50634336c9f9f6dc3d7e2f7c81de58c4f100976135811ebbd8db5ef0f0ead0f2'
    volumes:
      - ../..:/home/firestore-emulator
      - type: bind
        source: ../../firestore.rules
        target: /home/firebase-emulator/firestore.rules
    ports:
      - 4000:4000
      - 9150:9150
      - 4500:4500
      - 4400:4400
      - 9099:9099
      - 8080:8080
    healthcheck:
      timeout: 120s
    entrypoint:
      - "firebase"
      - "emulators:start"
      - "--project"
      - "map-librarian"
