version: "3.7"
services:
  firebase-emulator:
    image: 'ghcr.io/grodin/firebase-emulator-docker@sha256:dbe82a3ad7b0208f920bc50b38b1a219fbc3453ea0d53a41c9923fd1715aa872'
    volumes:
      - ../..:/home/firestore-emulator
      - type: bind
        source: ../../firestore.rules
        target: /home/firebase-emulator/firestore.rules
    ports:
      - 4000:4000
      - 9150:9150
      - 4500:4500
      - 4400:4400
      - 9099:9099
      - 8080:8080
    healthcheck:
      timeout: 120s
    entrypoint:
      - "firebase"
      - "emulators:start"
      - "--project"
      - "map-librarian"
