version: "3.7"
services:
  firebase-emulator:
    image: 'ghcr.io/grodin/firebase-emulator-docker@sha256:bc6b51ce63ee13151e28eaed93efed2ba644b1390b147b4e98af7c137d25b4b8'
    volumes:
      - ../..:/home/firestore-emulator
      - type: bind
        source: ../../firestore.rules
        target: /home/firebase-emulator/firestore.rules
    ports:
      - 4000:4000
      - 9150:9150
      - 4500:4500
      - 4400:4400
      - 9099:9099
      - 8080:8080
    healthcheck:
      timeout: 120s
    entrypoint:
      - "firebase"
      - "emulators:start"
      - "--project"
      - "map-librarian"
