name: Data layer integration tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  data-layer-integration-tests:
    name: Data layer integration tests run against Firebase emulator in Docker
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Start Firebase emulator and run integration tests
        run: scripts/data-layer-integration-tests.sh

