name: Data layer integration tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  data-layer-integration-tests:
    name: Data layer integration tests run against Firebase emulator in Docker

    # Use macos because GH linux runners don't have nested virtualization
    # Which is required to use gradle managed devices
    runs-on: macos-latest
    steps:

        # Docker can't be pre-installed on macos due to licensing issues so this is a workaround
      - name: Setup docker on macos
        run: |
          brew install docker
          colima start
          docker --version # Sanity check

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Start Firebase emulator and run integration tests
        run: scripts/data-layer-integration-tests.sh

