name: Pre Merge Checks

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - 'develop'
  pull_request:

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  gradle-validation:
    name: Gradle validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  ktfmt:
    name: 'Check *.kt *.kts with ktfmt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run ktfmt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ktfmtCheckAllKtsAndKt
          cache-read-only: false

  lint-detekt:
    name: Run lint and detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run lint
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintReportDebug lintReportRelease
          cache-read-only: false

      - name: Run detekt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detektAll
          cache-read-only: false

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Assemble all variants
        uses: gradle/gradle-build-action@v3
        with:
          arguments: app:assemble --continue
          cache-read-only: false

  jvm-tests:
    name: Run local tests for all projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run local tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test --continue --stacktrace
          cache-read-only: false
