name: Pre Merge Checks

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - 'develop'
  pull_request:

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  gradle-validation:
    name: Gradle validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v6
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

  ktfmt:
    name: 'Check *.kt *.kts with ktfmt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run ktfmt
        run: ./gradlew ktfmtCheckAllKtsAndKt

  lint-detekt:
    name: Run lint and detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run lint
        run: ./gradlew lintReportDebug lintReportRelease

      - name: Run detekt
        run: ./gradlew detektAll

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Assemble all variants
        run: ./gradlew app:assemble --continue

  jvm-tests:
    name: Run local tests for all projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run local tests
        run: ./gradlew test --continue --stacktrace
